### ISSUE TITLE
Branding: Replace logo files

### ISSUE THREAD

**Issue by viktorix** [ClassicPress/wp-cms-experimental#34]
One thing I realized just now, we never changed the file names of logo files. They still say `wordpress-logo.svg` in ClassicPress. I don't know what copyright/trademark implications this may or may not have, but we should do it correctly and change file names this time.

`wordpress-logo.svg|png`
- [x] src/wp-admin/css/install-rtl.css
- [x] src/wp-admin/css/install.css
- [x] src/wp-admin/css/login-rtl.css
- [x] src/wp-admin/css/login.css
- [x] src/readme.html

`wordpress-logo-white.svg`
- [x] src/wp-admin/css/about.css
- [x] src/wp-admin/css/about-rtl.css

`w-logo-white.png`
- [x] src/wp-admin/css/about.css
- [x] src/wp-admin/css/about-rtl.css

`w-logo-blue.png`
- [x] src/wp-admin/css/install-rtl.css
- [x] src/wp-admin/css/install.css
- [x] src/wp-admin/css/login-rtl.css
- [x] src/wp-admin/css/login.css
- [x] src/wp-includes/embed.php

`Misc. images`
- [x] 2 logo files in `\src\wp-includes\images`

**Comment by viktorix** [comment]
@mattyrob if I modify CSS files inside `wp-admin/css`, how are minified versions generated? 

For example, `src/wp-admin/css/install.css` and `src/wp-admin/css/install.min.css`.

**Comment by mattyrob** [comment]
Minified CSS and JS files are all created via `grunt build` and steps specified in Gruntfile.is

**Comment by bahiirwa** [comment]
> One thing I realized just now, we never changed the file names of logo files. They still say `wordpress-logo.svg` in ClassicPress. 
Related 
https://github.com/ClassicPress/ClassicPress/issues/172 
https://github.com/ClassicPress/ClassicPress/issues/266 
https://github.com/ClassicPress/ClassicPress-Design/pull/3 
https://github.com/ClassicPress/ClassicPress/pull/189

> I don't know what copyright/trademark implications this may or may not have, but we should do it correctly and change file names this time.
Worth considering with @KTS915 (GPL)

**Comment by KTS915** [comment]
There are no copyright or trademark implications for the names of these files.

**Comment by viktorix** [comment]
Thanks @KTS915 @bahiirwa 

My PR #39 includes renaming the files to properly use CP branding. If we don't want to make changes to 6 CSS/JS and 2 PHP files because of merge conflicts, I can change it back to what it was before. There are only eight files with file name changes.
